### ISSUE TITLE
Demo site 404s

### ISSUE THREAD

**Issue by bravo-kernel** [bnjmnt4n/reveal-code-focus#14]

**Comment by ldionne** [comment]
I don't get a 404, but I get that:

![screen shot 2017-09-09 at 13 13 14](https://user-images.githubusercontent.com/700834/30243561-c0e3da9c-9560-11e7-9465-1b8a6f6b026f.png)

**Comment by bnjmnt4n** [comment]
Hi, sorry for the very late reply. I've fixed the issue temporarily, and will take some time soon to ensure the site stays up on GitHub Pages. Here's a link to the demo: https://bnjmnt4n.github.io/reveal-code-focus/

**Comment by ldionne** [comment]
This is indeed working for me now
